const ALLOWED_ORIGINS = [
  'https://brassops.com',
  'https://www.brassops.com',
];

const LIMITS = {
  firstName: 100,
  email: 255,
  agency: 200,
};

const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// The three gated downloads. The PDFs are static files under /resources/pdf.
// The Brevo list for each one is found or created by NAME at request time
// (see brevoListId), so nothing here hard-codes a list id the way
// api/assessment.js does for the risk tiers.
const MAGNETS = {
  case_law: {
    label: 'Case Law One-Pager',
    list: 'Lead magnet · Case law',
    path: '/resources/pdf/case-law-one-pager.pdf',
    page: '/resources/case-law-one-pager',
    blurb: 'Five cases every firearms training officer should be able to cite, on one page, with what each one means for your training file.',
  },
  nj_checklist: {
    label: 'NJ Qualification Checklist',
    list: 'Lead magnet · NJ qual checklist',
    path: '/resources/pdf/nj-qualification-checklist.pdf',
    page: '/resources/nj-qualification-checklist',
    blurb: 'The New Jersey Attorney General semi-annual qualification requirements as a one-page checklist.',
  },
  sample_packet: {
    label: 'Sample Records Request Packet',
    list: 'Lead magnet · Sample packet',
    path: '/resources/pdf/sample-records-request-packet.pdf',
    page: '/resources/sample-records-request-packet',
    blurb: 'What a complete officer training file looks like when a subpoena arrives: a real packet generated by BrassOps for a fictional officer.',
  },
};

const BREVO_FOLDER = 'Lead magnets';
const SITE = 'https://brassops.com';

// ── Submission storage ───────────────────────────────────────────────────
// Same posture as api/assessment.js: persist BEFORE any provider is called,
// over plain fetch to PostgREST (no npm dependency, no package.json), and
// best effort, because the person is handed the PDF link regardless.

const SUPABASE_URL = (
  process.env.SUPABASE_URL ||
  process.env.NEXT_PUBLIC_SUPABASE_URL ||
  process.env.POSTGRES_SUPABASE_URL ||
  ''
).replace(/\/+$/, '');
const SERVICE_KEY =
  process.env.SUPABASE_SERVICE_ROLE_KEY ||
  process.env.SUPABASE_SERVICE_KEY ||
  process.env.POSTGRES_SUPABASE_SERVICE_ROLE_KEY;

const STORE_TABLE = 'lead_magnet_submissions';

function storageConfigured() {
  return Boolean(SUPABASE_URL && SERVICE_KEY);
}

async function sb(path, init = {}) {
  const r = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
    ...init,
    headers: {
      apikey: SERVICE_KEY,
      Authorization: `Bearer ${SERVICE_KEY}`,
      'Content-Type': 'application/json',
      ...(init.headers || {}),
    },
  });
  if (!r.ok) {
    const detail = await r.text().catch(() => '');
    throw new Error(`Supabase ${r.status}: ${detail.slice(0, 200)}`);
  }
  return r;
}

async function storeSubmission(record) {
  if (!storageConfigured()) {
    console.warn('Supabase not configured; lead magnet submission not persisted');
    return null;
  }
  try {
    const r = await sb(STORE_TABLE, {
      method: 'POST',
      headers: { Prefer: 'return=representation' },
      body: JSON.stringify(record),
    });
    const rows = await r.json();
    return (Array.isArray(rows) ? rows[0] : rows)?.id ?? null;
  } catch (err) {
    console.error('Failed to persist lead magnet submission:', err?.message);
    return null;
  }
}

async function markSubmission(id, status, detail) {
  if (id == null || !storageConfigured()) return;
  try {
    await sb(`${STORE_TABLE}?id=eq.${encodeURIComponent(id)}`, {
      method: 'PATCH',
      body: JSON.stringify({
        status,
        detail: detail == null ? null : (typeof detail === 'string' ? detail : JSON.stringify(detail)),
      }),
    });
  } catch (err) {
    console.error('Failed to update lead magnet submission status:', err?.message);
  }
}

// ── Brevo ────────────────────────────────────────────────────────────────

async function brevo(key, path, init = {}) {
  const r = await fetch(`https://api.brevo.com/v3${path}`, {
    ...init,
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/json',
      'api-key': key,
      ...(init.headers || {}),
    },
  });
  const text = await r.text().catch(() => '');
  let data = null;
  try { data = text ? JSON.parse(text) : null; } catch { data = null; }
  if (!r.ok) {
    throw new Error(`Brevo ${r.status} ${path}: ${text.slice(0, 200)}`);
  }
  return data;
}

// Find or create the "Lead magnets" folder. Nothing is cached: a serverless
// instance has no durable memory and the extra two or three GETs per
// download are cheap next to being wrong about a deleted folder.
async function brevoFolderId(key) {
  const PAGE = 50;
  for (let offset = 0; offset < 1000; offset += PAGE) {
    const data = await brevo(key, `/contacts/folders?limit=${PAGE}&offset=${offset}`);
    const folders = Array.isArray(data?.folders) ? data.folders : [];
    const hit = folders.find(f => f && f.name === BREVO_FOLDER);
    if (hit) return hit.id;
    if (folders.length < PAGE) break;
  }
  const created = await brevo(key, '/contacts/folders', {
    method: 'POST',
    body: JSON.stringify({ name: BREVO_FOLDER }),
  });
  if (created?.id == null) throw new Error('Brevo folder create returned no id');
  return created.id;
}

async function brevoListId(key, listName) {
  const folderId = await brevoFolderId(key);
  const PAGE = 50;
  for (let offset = 0; offset < 2000; offset += PAGE) {
    const data = await brevo(key, `/contacts/lists?limit=${PAGE}&offset=${offset}`);
    const lists = Array.isArray(data?.lists) ? data.lists : [];
    const hit = lists.find(l => l && l.name === listName);
    if (hit) return hit.id;
    if (lists.length < PAGE) break;
  }
  const created = await brevo(key, '/contacts/lists', {
    method: 'POST',
    body: JSON.stringify({ name: listName, folderId }),
  });
  if (created?.id == null) throw new Error('Brevo list create returned no id');
  return created.id;
}

async function brevoUpsertContact(key, { email, firstName, agency, magnet }) {
  const listId = await brevoListId(key, MAGNETS[magnet].list);
  const body = {
    email,
    attributes: {
      FIRSTNAME: firstName,
      AGENCY: agency || '',
      LEAD_MAGNET: magnet,
    },
    listIds: [listId],
    updateEnabled: true,
  };
  // POST with updateEnabled creates or updates (Brevo answers 201 or 204).
  await brevo(key, '/contacts', { method: 'POST', body: JSON.stringify(body) });
  return listId;
}

// ── SMTP2GO ──────────────────────────────────────────────────────────────

async function smtpSend(smtpKey, message) {
  const r = await fetch('https://api.smtp2go.com/v3/email/send', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ api_key: smtpKey, ...message }),
  });
  // SMTP2GO returns HTTP 200 even when a send is refused, so inspect the body.
  const data = await r.json().catch(() => null);
  if (data?.data?.succeeded > 0) return { ok: true };
  return {
    ok: false,
    detail: {
      httpStatus: r.status,
      errorCode: data?.data?.error_code ?? data?.error_code ?? null,
      error: data?.data?.error ?? data?.error ?? null,
      failures: data?.data?.failures ?? null,
    },
  };
}

function downloadEmailHtml({ firstName, magnet }) {
  const m = MAGNETS[magnet];
  const url = `${SITE}${m.path}`;
  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f5f5f7;">
    <tr>
      <td align="center" style="padding:24px 16px;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.06);">

          <!-- Header -->
          <tr>
            <td style="background:#0a0a0a;padding:24px 32px;text-align:center;">
              <div style="font-size:28px;font-weight:800;letter-spacing:2px;color:#ffffff;">Brass<span style="color:#ef4444">Ops</span></div>
              <div style="font-size:11px;font-weight:600;letter-spacing:2px;text-transform:uppercase;color:#888;margin-top:4px;">Range Intelligence Platform</div>
            </td>
          </tr>

          <!-- Intro -->
          <tr>
            <td style="padding:32px 32px 8px 32px;color:#1a1a1a;">
              <div style="font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#dc2626;margin-bottom:8px;">Your download</div>
              <div style="font-size:22px;font-weight:800;color:#0a0a0a;margin-bottom:16px;">${escapeHtml(m.label)}</div>
              <p style="font-size:16px;line-height:1.6;margin:0 0 12px 0;">Hi ${escapeHtml(firstName)},</p>
              <p style="font-size:15px;line-height:1.65;color:#444;margin:0 0 16px 0;">
                Here is the ${escapeHtml(m.label)} you asked for. ${escapeHtml(m.blurb)}
              </p>
            </td>
          </tr>

          <!-- Download button -->
          <tr>
            <td style="padding:8px 32px 24px 32px;text-align:center;">
              <a href="${url}" style="display:inline-block;background:linear-gradient(135deg,#ef4444,#dc2626);color:#ffffff;font-weight:700;letter-spacing:1px;text-transform:uppercase;font-size:14px;text-decoration:none;padding:14px 32px;border-radius:10px;">Open the PDF</a>
              <div style="font-size:12px;color:#888;margin-top:12px;">Or copy this link: <a href="${url}" style="color:#dc2626;text-decoration:none;">${url}</a></div>
            </td>
          </tr>

          <!-- Assessment pointer -->
          <tr>
            <td style="padding:0 32px 32px 32px;">
              <div style="background:linear-gradient(135deg,rgba(239,68,68,0.08),rgba(239,68,68,0.03));border:1px solid rgba(239,68,68,0.12);border-radius:12px;padding:20px 24px;text-align:center;">
                <div style="font-size:14px;color:#444;line-height:1.6;">Want to know where your own training file stands? Take the free two-minute <a href="${SITE}/assessment" style="color:#dc2626;font-weight:700;text-decoration:none;">Training Liability Risk Assessment</a>.</div>
              </div>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background:#fafafa;padding:24px 32px;text-align:center;border-top:1px solid #eeeeee;">
              <div style="font-size:13px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;color:#888;margin-bottom:4px;">Brass<span style="color:#ef4444">Ops</span></div>
              <div style="font-size:11px;color:#999;font-style:italic;margin-bottom:12px;">Built for those who train to protect.</div>
              <div style="font-size:11px;color:#aaa;">
                <a href="${SITE}/privacy" style="color:#888;text-decoration:none;margin:0 8px;">Privacy Policy</a>
                <a href="${SITE}/terms" style="color:#888;text-decoration:none;margin:0 8px;">Terms of Service</a>
              </div>
              <div style="font-size:10px;color:#bbb;margin-top:12px;">&copy; 2026 BrassOps. All rights reserved.</div>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

function downloadEmailText({ firstName, magnet }) {
  const m = MAGNETS[magnet];
  return [
    `Hi ${firstName},`,
    '',
    `Here is the ${m.label} you asked for.`,
    m.blurb,
    '',
    `Open the PDF: ${SITE}${m.path}`,
    '',
    'Want to know where your own training file stands? Take the free two-minute Training Liability Risk Assessment:',
    `${SITE}/assessment`,
    '',
    'BrassOps. Built for those who train to protect.',
    '(c) 2026 BrassOps',
  ].join('\n');
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Origin check
  const origin = req.headers.origin || req.headers.referer || '';
  const isAllowedOrigin =
    ALLOWED_ORIGINS.some(a => origin.startsWith(a)) ||
    origin.startsWith('http://localhost');
  if (origin && !isAllowedOrigin) {
    return res.status(403).json({ error: 'Forbidden' });
  }

  // Body validation
  if (!req.body || typeof req.body !== 'object') {
    return res.status(400).json({ error: 'Invalid request body' });
  }

  const { magnet, first_name, email, agency, website } = req.body;

  // Honeypot: answer as if it worked, hand out nothing.
  if (website) {
    return res.status(200).json({ ok: true });
  }

  if (typeof magnet !== 'string' || !Object.prototype.hasOwnProperty.call(MAGNETS, magnet)) {
    return res.status(400).json({ error: 'Unknown download' });
  }

  if (!first_name || !email) {
    return res.status(400).json({ error: 'Missing required fields' });
  }
  if (typeof first_name !== 'string' || typeof email !== 'string') {
    return res.status(400).json({ error: 'Invalid field types' });
  }
  if (agency != null && typeof agency !== 'string') {
    return res.status(400).json({ error: 'Invalid field types' });
  }

  const firstName = first_name.trim();
  const safeEmail = email.trim();
  const safeAgency = (agency || '').trim();

  if (!firstName || !safeEmail) {
    return res.status(400).json({ error: 'Missing required fields' });
  }
  if (firstName.length > LIMITS.firstName || safeEmail.length > LIMITS.email || safeAgency.length > LIMITS.agency) {
    return res.status(400).json({ error: 'Input exceeds maximum length' });
  }
  if (!EMAIL_REGEX.test(safeEmail)) {
    return res.status(400).json({ error: 'Invalid email format' });
  }

  const m = MAGNETS[magnet];
  const pdfUrl = m.path;
  const result = { ok: true, url: pdfUrl };

  // Persist before any provider call, and before the API key checks, so a
  // misconfiguration still leaves the lead recoverable.
  const submissionId = await storeSubmission({
    status: 'pending',
    magnet,
    first_name: firstName,
    email: safeEmail,
    agency: safeAgency || null,
    ip: clientIp(req),
    user_agent: String(req.headers['user-agent'] || '').slice(0, 400) || null,
  });

  const smtpKey = process.env.SMTP2GO_API_KEY;
  const brevoKey = process.env.BREVO_API_KEY;
  const recipient = process.env.CONTACT_RECIPIENT || 'info@brassops.com';

  const problems = {};

  // ── Brevo: folder, list, contact ──
  if (brevoKey) {
    try {
      const listId = await brevoUpsertContact(brevoKey, { email: safeEmail, firstName, agency: safeAgency, magnet });
      result.listId = listId;
    } catch (err) {
      console.error('Brevo lead magnet sync failed:', err?.message);
      problems.brevo = err?.message ?? 'request failed';
    }
  } else {
    console.warn('BREVO_API_KEY not configured; lead magnet contact not synced');
    problems.brevo = 'BREVO_API_KEY not configured';
  }

  if (!smtpKey) {
    console.error('SMTP2GO_API_KEY not configured');
    problems.smtp = 'SMTP2GO_API_KEY not configured';
    await markSubmission(submissionId, 'failed', problems);
    return res.status(200).json(result);
  }

  const safeFirst = firstName.replace(/[\r\n]/g, '').slice(0, 50);
  const safeAgencySubject = (safeAgency || 'unknown agency').replace(/[\r\n]/g, '').slice(0, 80);

  // ── Download email to the person ──
  try {
    const sent = await smtpSend(smtpKey, {
      to: [safeEmail],
      sender: 'BrassOps <noreply@brassops.com>',
      subject: `Your BrassOps download: ${m.label}`,
      html_body: downloadEmailHtml({ firstName, magnet }),
      text_body: downloadEmailText({ firstName, magnet }),
    });
    if (!sent.ok) {
      console.error('SMTP2GO download email rejected', sent.detail);
      problems.downloadEmail = sent.detail;
    }
  } catch (err) {
    console.error('SMTP2GO download email failed:', err?.message);
    problems.downloadEmail = { error: err?.message ?? 'request failed' };
  }

  // ── Admin notification ──
  const adminHtmlBody = `
    <h2 style="color:#0a0a0a;font-family:sans-serif;">New Lead Magnet Download</h2>
    <table style="border-collapse:collapse;width:100%;max-width:600px;font-family:sans-serif;">
      <tr><td style="padding:8px 12px;font-weight:bold;color:#555;border-bottom:1px solid #eee;">Download</td><td style="padding:8px 12px;border-bottom:1px solid #eee;font-weight:700;">${escapeHtml(m.label)}</td></tr>
      <tr><td style="padding:8px 12px;font-weight:bold;color:#555;border-bottom:1px solid #eee;">Name</td><td style="padding:8px 12px;border-bottom:1px solid #eee;">${escapeHtml(firstName)}</td></tr>
      <tr><td style="padding:8px 12px;font-weight:bold;color:#555;border-bottom:1px solid #eee;">Email</td><td style="padding:8px 12px;border-bottom:1px solid #eee;"><a href="mailto:${escapeHtml(safeEmail)}">${escapeHtml(safeEmail)}</a></td></tr>
      <tr><td style="padding:8px 12px;font-weight:bold;color:#555;border-bottom:1px solid #eee;">Agency</td><td style="padding:8px 12px;border-bottom:1px solid #eee;">${escapeHtml(safeAgency || 'Not given')}</td></tr>
      <tr><td style="padding:8px 12px;font-weight:bold;color:#555;border-bottom:1px solid #eee;">Brevo list</td><td style="padding:8px 12px;border-bottom:1px solid #eee;">${escapeHtml(m.list)}${result.listId != null ? ` (#${result.listId})` : ' (sync failed)'}</td></tr>
    </table>
    <p style="margin-top:20px;font-family:sans-serif;font-size:13px;color:#888;">This lead requested a download from ${escapeHtml(SITE + m.page)}</p>
  `;
  const adminTextBody = [
    'NEW LEAD MAGNET DOWNLOAD',
    `Download: ${m.label}`,
    `Name: ${firstName}`,
    `Email: ${safeEmail}`,
    `Agency: ${safeAgency || 'Not given'}`,
    `Brevo list: ${m.list}${result.listId != null ? ` (#${result.listId})` : ' (sync failed)'}`,
    `Page: ${SITE}${m.page}`,
  ].join('\n');

  try {
    const sent = await smtpSend(smtpKey, {
      to: [recipient],
      sender: 'BrassOps Lead Magnet <noreply@brassops.com>',
      subject: `Lead Magnet: ${safeFirst} at ${safeAgencySubject} downloaded ${m.label}`,
      html_body: adminHtmlBody,
      text_body: adminTextBody,
    });
    if (!sent.ok) {
      console.error('SMTP2GO admin email rejected', sent.detail);
      problems.adminEmail = sent.detail;
    }
  } catch (err) {
    console.error('SMTP2GO admin email failed:', err?.message);
    problems.adminEmail = { error: err?.message ?? 'request failed' };
  }

  if (Object.keys(problems).length === 0) {
    await markSubmission(submissionId, 'sent');
  } else {
    // The download email reaching the person is what "sent" means here; a
    // Brevo or admin-notice failure is recorded but does not fail the row.
    await markSubmission(submissionId, problems.downloadEmail ? 'failed' : 'sent', problems);
  }

  // Always ok with the url: the person is never stuck behind a provider.
  return res.status(200).json(result);
}

function clientIp(req) {
  const fwd = req.headers['x-forwarded-for'];
  if (typeof fwd === 'string' && fwd.length) return fwd.split(',')[0].trim();
  return req.headers['x-real-ip'] || 'unknown';
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
